spring:
  application:
    name: backend-spring

server:
  port: 8088
  # TODO: hmm, local cert not present....deactivate at local dev via profile?
  ssl:
    key-store: "/etc/letsencrypt/live/facemirrored.de/keystore.p12"
    key-store-password: "*gPs9UTqf2@5cUdRdH*teJX&R2GDuFb9"
    key-store-type: "PKCS12"
    key-alias: "tomcat"